const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const html = fs.readFileSync('bonaventure/ui/review.html', 'utf8');
const source = html.match(/function openTech\(\) \{[\s\S]*?\n\}/)[0];
const nodes = {modalBox: {}, modal: {classList: {add(){}}}};
const context = { C: {case_id: 'BV-test', technical: {models:[],timing:{},raw_reasoning:['', '[natural-language understanding] rewrite']}, quality:{state:'acceptable',metrics:{}}}, sel:null, $:id=>nodes[id], cap:x=>x, esc:x=>String(x).replaceAll('<','&lt;') };
vm.createContext(context);
vm.runInContext(source, context);
context.openTech();
assert.match(nodes.modalBox.innerHTML, /No MedGemma image response was saved/);
assert.match(nodes.modalBox.innerHTML, /Clinical rewriting output/);
context.C.technical.raw_reasoning = ['{"findings": []} <test>', '[natural-language understanding] rewrite'];
context.openTech();
assert.match(nodes.modalBox.innerHTML, /findings/);
assert.match(nodes.modalBox.innerHTML, /&lt;test>/);
assert.doesNotMatch(nodes.modalBox.innerHTML, /No MedGemma image response/);
console.log('Review raw output checks passed: empty responses, clinical/image separation and escaped output.');
